# Generated by Django 4.2.8 on 2023-12-27 05:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multiuser', '0002_organisationuser_organisation_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganisationUser',
            new_name='OrganisationAssignment',
        ),
    ]
