# Generated by Django 5.0 on 2023-12-31 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiuser', '0008_alter_branch_created_by_alter_business_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='address',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='business',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='email',
        ),
        migrations.RemoveField(
            model_name='business',
            name='established_date',
        ),
        migrations.RemoveField(
            model_name='business',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='business',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='email',
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_fields',
            field=models.CharField(default='Branch-specific fields', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multiuser.branch'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_fields',
            field=models.CharField(default='Information specific to businesses', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multiuser.business'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_fields',
            field=models.CharField(default='Information specific to organisations', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multiuser.organisation'),
        ),
    ]
