# Generated by Django 5.0 on 2023-12-31 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiuser', '0009_remove_branch_address_remove_branch_business_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='id',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='name',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='business',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='business',
            name='id',
        ),
        migrations.RemoveField(
            model_name='business',
            name='name',
        ),
        migrations.RemoveField(
            model_name='business',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='parent',
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multiuser.entity')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='entity_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multiuser.entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='entity_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multiuser.entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='entity_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multiuser.entity'),
            preserve_default=False,
        ),
    ]
