# Generated by Django 5.0.1 on 2024-01-06 11:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiuser', '0011_inviteduser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvitedUser',
            new_name='Invitation',
        ),
    ]
