# Generated by Django 5.0.1 on 2024-01-14 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('multiuser', '0012_rename_inviteduser_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='content_type',
            field=models.ForeignKey(default=7, editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='object_id',
            field=models.PositiveIntegerField(default=6, editable=False),
            preserve_default=False,
        ),
    ]
