# Generated by Django 5.0.1 on 2024-01-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiuser', '0013_entity_content_type_entity_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='entity_ptr',
        ),
        migrations.RemoveField(
            model_name='business',
            name='entity_ptr',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='entity_ptr',
        ),
        migrations.AddField(
            model_name='branch',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
