# Generated by Django 5.0.1 on 2024-01-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiuser', '0014_remove_branch_entity_ptr_remove_business_entity_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='name',
        ),
    ]
