# Generated by Django 5.0.1 on 2024-01-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiuser', '0015_remove_entity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(default='orgbizbr', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='name',
            field=models.CharField(default='biz', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='name',
            field=models.CharField(default='org', max_length=100),
            preserve_default=False,
        ),
    ]
