# Generated by Django 5.0.1 on 2024-01-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiuser', '0016_branch_name_business_name_organisation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='invited_by',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
